export {
  svg,
  line,
  polygon,
  polyline,
  circle,
  ellipse,
  rect,
  label,
  dot,
  type SvgStyle,
  type SvgLabelStyle,
} from './primitives';

export {
  rightTriangle,
  triangleGeneric,
  triangleBaseHeight,
  equilateralTriangleFigure,
  trapezoid,
  squareFigure,
  rectangleFigure,
  circleFigure,
  regularPolygonFigure,
  coordinatePlane,
  sphereSilhouette,
  cylinderSilhouette,
  coneSilhouette,
  pyramidSilhouette,
  rectangularPrismSilhouette,
  cubeSilhouette,
  compositeRectangleTriangle,
  type RightTriangleParams,
  type TriangleGenericParams,
  type TrapezoidParams,
  type CoordinatePlaneParams,
} from './archetypes';
